### ISSUE TITLE
any plan to support the real private repository

### ISSUE THREAD

**Issue by kenizhou** [microsoft/winget-cli-restsource#165] opened 2022-09-12 01:24 UTC
### Description of the new feature / enhancement

It's meaningless to host the repository on the MS azure, when company want to setup their own repository.

Any plan to support real local setup, e.g. Support Local database. Thanks!

**Comment by denelon** [comment] 2022-09-14 23:57
Duplicate of #158

or #135

**Closed** 2022-09-14 23:57 UTC
Labels: Issue-Feature
